export enum OrderStatusEnum {
  CREATED = 'CREATED',
  NEED_CHANGES = 'NEED_CHANGES',
  APPROVED = 'APPROVED',
  PAYED = 'PAYED',
  IN_PROGRESS = 'IN_PROGRESS',
  DECLINED = 'DECLINED',
  COMPLETED = 'COMPLETED'
}
