spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      dialect: PostgreSQLDialect
      format_sql: true
    hibernate:
      ddl-auto: none